/* eslint-disable @typescript-eslint/no-unused-vars */
// @ts-nocheck
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/

export const commands = {
  async readDirectory(path: string): Promise<Result<FileEntry[], string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("read_directory", { path }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async getDrives(): Promise<Result<DriveInfo[], string>> {
    try {
      return { status: "ok", data: await TAURI_INVOKE("get_drives") };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async createDirectory(path: string): Promise<Result<null, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("create_directory", { path }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async createFile(path: string): Promise<Result<null, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("create_file", { path }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async deleteEntries(
    paths: string[],
    permanent: boolean
  ): Promise<Result<null, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("delete_entries", { paths, permanent }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async renameEntry(
    oldPath: string,
    newName: string
  ): Promise<Result<string, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("rename_entry", { oldPath, newName }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async copyEntries(
    sources: string[],
    destination: string
  ): Promise<Result<null, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("copy_entries", { sources, destination }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async moveEntries(
    sources: string[],
    destination: string
  ): Promise<Result<null, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("move_entries", { sources, destination }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async getFileContent(path: string): Promise<Result<string, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("get_file_content", { path }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async getParentPath(path: string): Promise<Result<string | null, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("get_parent_path", { path }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async pathExists(path: string): Promise<Result<boolean, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("path_exists", { path }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async searchFiles(
    options: SearchOptions
  ): Promise<Result<SearchResult[], string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("search_files", { options }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async searchByName(
    searchPath: string,
    query: string,
    maxResults: number | null
  ): Promise<Result<SearchResult[], string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("search_by_name", {
          searchPath,
          query,
          maxResults,
        }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async searchContent(
    searchPath: string,
    query: string,
    extensions: string[] | null,
    maxResults: number | null
  ): Promise<Result<SearchResult[], string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("search_content", {
          searchPath,
          query,
          extensions,
          maxResults,
        }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
};

/** user-defined events **/

/** user-defined constants **/

/** user-defined types **/

export type ContentMatch = {
  line_number: number;
  line_content: string;
  match_start: number;
  match_end: number;
};
export type DriveInfo = {
  name: string;
  path: string;
  total_space: number;
  free_space: number;
  drive_type: string;
};
export type FileEntry = {
  name: string;
  path: string;
  is_dir: boolean;
  is_hidden: boolean;
  size: number;
  modified: number | null;
  created: number | null;
  extension: string | null;
};
export type SearchOptions = {
  query: string;
  search_path: string;
  search_content: boolean;
  case_sensitive: boolean;
  max_results: number | null;
  file_extensions: string[] | null;
};
export type SearchResult = {
  path: string;
  name: string;
  is_dir: boolean;
  matches: ContentMatch[];
};

/** tauri-specta globals **/

import {
  invoke as TAURI_INVOKE,
  Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
  listen: (
    cb: TAURI_API_EVENT.EventCallback<T>
  ) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
  once: (
    cb: TAURI_API_EVENT.EventCallback<T>
  ) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
  emit: null extends T
    ? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
    : (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
  | { status: "ok"; data: T }
  | { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
  mappings: Record<keyof T, string>
) {
  return new Proxy(
    {} as unknown as {
      [K in keyof T]: __EventObj__<T[K]> & {
        (handle: __WebviewWindow__): __EventObj__<T[K]>;
      };
    },
    {
      get: (_, event) => {
        const name = mappings[event as keyof T];

        return new Proxy((() => {}) as any, {
          apply: (_, __, [window]: [__WebviewWindow__]) => ({
            listen: (arg: any) => window.listen(name, arg),
            once: (arg: any) => window.once(name, arg),
            emit: (arg: any) => window.emit(name, arg),
          }),
          get: (_, command: keyof __EventObj__<any>) => {
            switch (command) {
              case "listen":
                return (arg: any) => TAURI_API_EVENT.listen(name, arg);
              case "once":
                return (arg: any) => TAURI_API_EVENT.once(name, arg);
              case "emit":
                return (arg: any) => TAURI_API_EVENT.emit(name, arg);
            }
          },
        });
      },
    }
  );
}
